<?php

namespace AppBundle\Repository;

/**
 * CatedraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatedraRepository extends \Doctrine\ORM\EntityRepository
{

}
