<?php

namespace AppBundle\Repository;

/**
 * EtiquetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtiquetaRepository extends \Doctrine\ORM\EntityRepository
{
}
