<?php

namespace AppBundle\Repository;

/**
 * ModificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
