<?php

namespace AppBundle\Repository;

/**
 * NoticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaRepository extends \Doctrine\ORM\EntityRepository
{
	public function notciasActuales() {

		$fechaActual = new \DateTime("now");

		$qb = $this->createQueryBuilder('n')
			->where('n.fechaCaducidad > :fechaActual')->setParameter('fechaActual', $fechaActual);
		return $qb->getQuery()->getResult();

	}
}
