<?php

namespace AppBundle\Repository;

/**
 * PublicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionRepository extends \Doctrine\ORM\EntityRepository
{
	public function publicacionesActuales() {

		$fechaActual = new \DateTime("now");

		$qb = $this->createQueryBuilder('p')
			->where('p.fechaCaducidad > :fechaActual')->setParameter('fechaActual', $fechaActual);
		return $qb->getQuery()->getResult();

	}
}
